apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: opposite-buzzard-nodejs-gitops
  description: This is GitOps manifest for opposite-buzzard-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: opposite-buzzard-nodejs
    janus-idp.io/tekton: opposite-buzzard-nodejs 
    backstage.io/kubernetes-id: opposite-buzzard-nodejs 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:opposite-buzzard-nodejs
