apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: opposite-buzzard-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: opposite-buzzard-nodejs 
  name: opposite-buzzard-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: opposite-buzzard-nodejs 
